### ISSUE TITLE
Qn about Shopify Theme Inspector and Scope of Support 

### ISSUE THREAD

**Issue by Alfashero** [Shopify/shopify-theme-inspector#105]
### Problem

``
DevTools failed to load source map: Could not load content for https://cdn.shopify.com/s/trekkie.storefront.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for https://cdn.shopify.com/shopifycloud/shopify-xr-js/v1.0/bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/sw-www-authdesktop.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/workbox-precaching.prod-c9d8c403a8a2d2df.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/workbox-sw-49788b12e8ffa47d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/workbox-core.prod-da0b69af4d8ad8a3.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/workbox-routing.prod-1f85f744c0ecb34d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://sm.pinimg.com/webapp/workbox-strategies.prod-fa8ffe3cde8c6c73.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
starcadia-quest-nayomi-tanaka-kickstarter-edition-board-game-expansion:1 The resource https://cdn.shopify.com/s/files/1/1915/6645/files/TGS_Logo_600x.png?v=1619993151 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

```

**Comment by Alfashero** [comment]
[Guru Card](https://app.getguru.com/card/ia46MejT/Shopify-Theme-and-Liquid-Inspector-for-Chrome)

**Comment by wizardlyhel** [comment]
Answered in a different channel
