### ISSUE TITLE
Shopify extension won't log in

### ISSUE THREAD

**Issue by Vickyw79** [Shopify/shopify-theme-inspector#115]
### Problem

/* Succinct outline of the problem or request. */

### Replication steps

/* How to replicate the problem. Include screenshots or video if relevant. */

### More Information

/* Any additional information which might be helpful. */

**Comment by jonaswebdev** [comment]
I have a similar issue on Chrome Dev but works well when I use regular Chrome... if anyone has interest on investigate this issue I could provide more details even a video of the screen to demonstrate the issue
