### ISSUE TITLE
Issue with layout folder path

### ISSUE THREAD

**Issue by onkar4058** [Shopify/shopify-theme-inspector#133]
### Problem
When clicking on the Shopify file it takes you to the wrong path layouts/theme. liquid

/* Succinct outline of the problem or request. */

### Replication steps

/* How to replicate the problem. Include screenshots or video if relevant. */
![image](https://github.com/Shopify/shopify-theme-inspector/assets/51198725/0fbef187-840b-4179-a087-c639496d5bff)
![image](https://github.com/Shopify/shopify-theme-inspector/assets/51198725/3911b6cf-63d4-40f7-b37c-7bee43d938df)

### More Information

/* Any additional information which might be helpful. */

**Comment by merziy** [comment]
I think this repository has been abandoned :(

The official docs still [recommend its use](https://shopify.dev/docs/themes/tools/theme-inspector) for identifying Liquid that is not optimal, and it seems like a lot of reviewers on the [chome web store](https://chrome.google.com/webstore/detail/shopify-theme-inspector-f/fndnankcflemoafdeboboehphmiijkgp) are mentioning problems with the extension.

**Comment by mgmanzella** [comment]
closing as fixed, redirects were also recently updated and tested https://github.com/Shopify/shopify-theme-inspector/pull/143
