### ISSUE TITLE
After latest update detailed information on each piece of code has disappeared

### ISSUE THREAD

**Issue by AlexHodzitsky** [Shopify/shopify-theme-inspector#147]
Hi there.

After latest update detailed render information on each piece of code has disappeared. 

Before under each section / snippet it was possible to see each code snippet, like {{ product.price | json }} and it's render time. But now there is only 3 levels of the inspect: Page > template > section and nothing under section.

![Image](https://github.com/user-attachments/assets/d029b82f-5b30-49dd-a0cf-559fcaad7325)

**Comment by mgmanzella** [comment]
👋 thanks for raising folks, taking a look now

**Comment by mgmanzella** [comment]
should be fixed now (you may have to refresh the profile button a couple times) -- thanks again for raising
