### ISSUE TITLE
Page speed Issue

### ISSUE THREAD

**Issue by Soumyadevsh** [Shopify/shopify-theme-inspector#148]
Hi Team,
   We are using the sense theme and it is up to date. We have increased our traffic after that the page loading time increases on our shopify store. So is our theme is compatible for the performance part as well. Can you suggest any method to low down the loading speed?![Image](https://github.com/user-attachments/assets/0bb85ca2-0bc0-4651-bffc-e78c543ce81c)

**Comment by mgmanzella** [comment]
👋 thanks for reaching out, we aren't equipped to give you advice about improving your CWV scores. i recommend following up with [the performance team at Shopify](https://performance.shopify.com/pages/services) who can give you some recommendations.
