### ISSUE TITLE
Log in doesn't work

### ISSUE THREAD

**Issue by wizardlyhel** [Shopify/shopify-theme-inspector#32]
### Known Issues

* Partner collaborator accounts with shop permissions will not log in (Fixed - May 27, 2020)

Shopify is planning to work on this issue but there is no timeline on when this will be fix.

**Comment by curiouscrusher** [comment]
+1 for the ability to use collaborator accounts!

Until that's supported this is nice, but likely not very useful for the majority of Plus Partner agencies who rely on collaborator accounts.

**Comment by pvidali** [comment]
Presumably the majority of the potential users of this extension have Partner or collaborator accounts, so without it, this extension doesn't make a lot of sense.

**Comment by wizardlyhel** [comment]
Curious for those that is on this thread - Does this extension works for you on development stores?

**Comment by dan-gamble** [comment]
It doesn't for me on a development store via a partners account.

**Comment by wizardlyhel** [comment]
Thanks for the information @dan-gamble

**Comment by Ben-Abbes** [comment]
@wizardlyhel Unfortunately, it doesn't even work with a  staff account. waste 3 hours just trying to make it work

**Comment by wizardlyhel** [comment]
@Ben-Abbes Thanks for flagging

**Comment by jonathanmoore** [comment]
Hopefully, a solution for Partner accounts will roll out soon.  On a daily basis, I look into over a dozen of these performance issues as a part of premium theme support.  In every case, the issue comes down to a Shopify App that is very poorly optimized brings the TTFB for collections up to 30 seconds.  Right now the process of pinpointing the cause to direct the merchant to the right Shopify App is an effort of manual trial and error.

**Comment by curiouscrusher** [comment]
It looks like #53 may have added this functionality, based on a recent [changelog update](https://shopify.dev/changelog/shopify-theme-inspector-for-chrome-now-supports-collaborator-account-access) posted earlier today. Looking forward to testing it out!

**Comment by wizardlyhel** [comment]
Shopify Collaborator accounts are working!

If you are managing a store as a Shopify partner collaborator with full or theme access, you can now profile your managed stores!

We are still working on getting access to development stores

**Comment by wizardlyhel** [comment]
For development store issue, I have created a separate issue to follow https://github.com/Shopify/shopify-theme-inspector/issues/55
