### ISSUE TITLE
No console errors, but "This page cannot be profiled"

### ISSUE THREAD

**Issue by rickydazla** [Shopify/shopify-theme-inspector#33]
### Problem

🔥 I would lurve to use this, but although I am logged-in and don't have any console errors, the Shopify tab returns "This page cannot be profiled". Any suggested steps for debugging??

**Comment by rickydazla** [comment]
https://www.taylorstitch.com/

**Comment by tehaksbrid** [comment]
Same, on plus both with full access and owner account credentials.

**Comment by brendanthrive** [comment]
My team is having the same issue - thrivecausemetics.com

**Comment by kieranmasterton** [comment]
Same issues here on the three stores I've tested. In the inspector I can see the request to `/?profile_liquid=true` succeeds but then the console reports the following error: 

`Error: Liquid profile not found for this page`

**Comment by wizardlyhel** [comment]
Thanks for reporting the issue - I'm looking into this issue.

If there is a domain redirect on the domain, for example ...

taylor-stitch.myshopify.com => www.taylorstitch.com

The liquid profiling will show the message "Liquid profile not found for this page" even if the logged in account is a staff account.

**Comment by ConduciveMammal** [comment]
I too was getting this error.
I got it working by going to xxxx.myshopify.com**?_ft=0**. This forces the domain to not redirect to the .com custom domain. It then works.

This should really be added into the README.

**Comment by mark-netalico** [comment]
@ConduciveMammal That trick isn't working for me to prevent the redirect. Any secrets to getting it to work?

**Comment by tehaksbrid** [comment]
After I disabled the redirect for our store, I was able to get this working.

**Comment by djpaoloc** [comment]
doesn't works if logged like partner.
