### ISSUE TITLE
Freezing issue

### ISSUE THREAD

**Issue by lukechadwick** [Shopify/shopify-theme-inspector#35]
### Problem

After profiling a page, mousing over/clicking the bars where a loading time bubble is shown locks up the extension

### Replication steps

Happening to me on homepage of https://www.alphalion.com/
https://screenshot.click/16-52-35tmi-8w6o5.mp4

This doesn't happen on my test store with a fairly vanilla theme.

### More Information
No errors in the extension's console. Currently this store is having issues with their header liquid code causing a slow load, so I'm suspect it's looping too much, which might be overloading this tool by putting too many elements into the graph:
https://screenshot.click/16-49-pmwxg-nx5ow.png
Though that's a scenario that this tool should help to investigate so ideally this can be overcome.

**Comment by wizardlyhel** [comment]
Thanks for flagging this

**Comment by gil--** [comment]
I'm seeing this similar behavior on pages where there's a lot of nested loops (basically a non performant page). So for instance, homepage flame graph loads fine and can interactive but on a PDP where we merge products together, the flame graph freezes and we're unable to interact.

**Comment by wizardlyhel** [comment]
@gil-- Would you be able to share the url of the store?

The more examples that we can test this tool on, the more that we can create insights on what kind of liquid pattern are being used to achieve different results. This tool is still in its early stage of discovery of what can we learn from knowing the liquid profiling time.

**Comment by gil--** [comment]
@wizardlyhel Sure, happy to share the url. We're actively working to improve some of the performance as it's for an unreleased Shopify Plus store. Is there any email @shopify I can use as I'd rather not disclose publicly.

**Comment by wizardlyhel** [comment]
Feel free to private message me on twitter @wizardlyhel

**Comment by wizardlyhel** [comment]
@lukechadwick I tried to reproduce the freezing chart issue. I am not able to reproduce it. This may due to some fixes that I have roll out today which you will be able to try again with version 1.0.2 in a couple days when Google approves the review.

I do admit that the D3 flamechart library is not working smoothly with this many nodes

**Comment by wizardlyhel** [comment]
Fixed https://github.com/Shopify/shopify-theme-inspector/pull/40

It'll take some time for Google review this update. Look forward to v1.0.3 update in 10 business days.
