### ISSUE TITLE
Incompatible with unpublished themes

### ISSUE THREAD

**Issue by tehaksbrid** [Shopify/shopify-theme-inspector#36]
### Problem

When attempting to profile an unpublished theme, results for the published theme are computed instead.

### Replication steps

1. Load up a preview for an unpublished theme that has obvious liquid differences from the main theme.
2. Attempt profiling, inspect the profiler in devtools and replay the `profile_liquid=true` request via fetch, but add the parameters `fts=0&preview_theme_id=${themeId}`. 
3. Resolve to text
4. Extract the json from the `#liquidProfileData` container.
5. Compare to what the profiler provided and you'll find the wrong theme was profiled.

### More Information

Thanks for the amazing tool. This is really amazing to finally have.

**Comment by wizardlyhel** [comment]
Hi @tehaksbrid , I am unable to reproduce this issue. I am getting 2 different timing profiles with published and unpublished themes. You should be able to visually see the profiling difference by profiling one of the theme in an incognito window.

<img width="1061" alt="Screen Shot 2020-01-27 at 4 51 28 PM" src="https://user-images.githubusercontent.com/2319002/73226558-5f7f6000-4125-11ea-82d2-db7d408bad2d.png">

**Comment by tehaksbrid** [comment]
Huh. Sorry, I thought I had tested that pretty thoroughly before posting. Evidently not. Thank you for checking into it!

**Comment by tehaksbrid** [comment]
Hey, sorry to resurrect this @wizardlyhel,  but...I'm consistently seeing this happen again. I should have explained more in my original issue. What I am really seeing:

**Changes to my liquid code are not being reflected in the flame graph**

Before, I assumed that this was due to the extension referencing the wrong theme.
This time, I'm emptying entire files and the flame graph isn't budging.

![flamegraph](https://user-images.githubusercontent.com/22158488/73695762-c44c3480-46a8-11ea-9e42-dad3bff01230.PNG)

`section:featured-collection` has been an empty file in this theme for about 30 minutes. The flame graph is still identical to the production site. 

My exact process has been:

1. Profile published theme in normal Chrome via our custom domain
2. Go incognito and profile unpublished theme via our custom domain
3. Delete a lot of code from unpublished theme
4. Profile...restart chrome...profile...delete more code...profile...nothing changes for the unpublished theme's profile

I have a HAR export I can share with you privately if that will help. In the HAR, I did notice -- the liquid profile data (#liquidProfileData) is missing from the document `?profile_liquid=true` loaded. The extension is still showing me a flame graph and timing data though...

I finally tried using our myshopify domain and **this worked**. I thought this issue was resolved in 1.01, so I didn't end up trying for a while.

**Comment by wizardlyhel** [comment]
Ahh yea, version 1.02 is where it was fixed

**Comment by tehaksbrid** [comment]
I was using 1.02 in my most recent comment. I replicated just now with 1.02 --

1. Profile published theme via custom domain
2. In **same browser window**, paste link to unpublished theme with significant liquid changes @ custom domain
3. Re-profile. I get results for theme from step #1.
4. In **same browser window**, change domain to .myshopify
5. Re-profile. I get the expected profile.
