### ISSUE TITLE
Plugin injects code into non-html rendering

### ISSUE THREAD

**Issue by ewalk153** [Shopify/shopify-theme-inspector#43]
### Problem

I was checking out the Shopify changelog XML feed and saw this text at the bottom of the page:
```
window.postMessage({ hasDetectedShopify: typeof window.Shopify !== 'undefined', }, '*');
```
Turns out that the plugin is indiscriminately injecting it's script tag into the page. 

### Replication steps

1. Visit https://changelog.shopify.com/feed.xml
2. See `window.postMessage({ hasDetectedShopify: typeof window.Shopify !== 'undefined', }, '*');` at the bottom of the page

### More Information

/* Any additional information which might be helpful. */

**Comment by wizardlyhel** [comment]
@ewalk153 Thanks for noting this!
