### ISSUE TITLE
This page cannot be profiled (suspected theme problem)

### ISSUE THREAD

**Issue by susanlangenes** [Shopify/shopify-theme-inspector#44]
### Problem

Cannot use on Shopify Plus site with custom domain nor on their staging/dev site without custom domain.  Both the live site and the dev site are using versions of the same theme (Brooklyn, pretty heavily modified).

Tried using the .myshopify.com domain, tried adding ?_ft=0; in all cases I get some variation of the following:

```
Error: Liquid profile not found for this page
  at devtools.js:8
  (etc)
SyntaxError: Unexpected token ' in JSON at position 330617 (this number varies)
```
(see screenshot for more complete errors)
![Screen Shot 2020-02-04 at 1 18 04 PM](https://user-images.githubusercontent.com/2976309/73789057-f3b77b80-4752-11ea-8ef8-f4c43f2fbd12.png)

### Replication steps

I can't replicate this on other Shopify sites.  So I think it's a problem with the theme, because:
Works fine with two completely different stores.
Works when theme in dev store is changed to an unedited version of Brooklyn.

Likely this is actually a feature request: can this supply more information as to where the JSON syntax error can be found and fixed?

**Comment by tom-it** [comment]
we have the same issue on a plus store, no error message, using turbo theme

**Comment by wizardlyhel** [comment]
With errors from the theme itself, we are aware sections architecture doesn't work yet. I would like know the url of the sites so that I can debug on it. Please private tweet me the shop url [@wizardlyhel](https://twitter.com/wizardlyhel) if you do not want to post it here.

**Comment by lukechadwick** [comment]
@wizardlyhel

I've experienced a variant of this issue.  I had a product page that was taking about 15 seconds to render, trying to use the tool would result in this error.  However after removing some snippets the manual way with some guess work and getting the page loading fast again, the tool works fine.

I was able to isolate it to one snippet and it would seem that either the complexity of the loop, or the code specific to that snippet(bold-product.liquid) is breaking something in the tool.

Interestingly this snippet is also included on the homepage though doesn't cause an issue with the tool, so it might be some of the product page specific code within the snippet that is causing issue.

**Comment by wizardlyhel** [comment]
@susanlangenes @lukechadwick A fix is on its way

**Comment by susanlangenes** [comment]
@wizardlyhel do you still want a link to the store/theme where my issue is happening? Missed your original ask.

**Comment by wizardlyhel** [comment]
Should be fine without sharing. We were able to reproduce the broken JSON issue. I'll ping this thread once the fix is out. There is no need to update extension for this fix.

**Comment by wizardlyhel** [comment]
@susanlangenes @lukechadwick The fix is live!

**Comment by susanlangenes** [comment]
@wizardlyhel Fantastic! Thank you so much! Tested on my problem site, and it is working beautifully.
