### ISSUE TITLE
It is not possible to get data from Managed Stores (as a Partner)

### ISSUE THREAD

**Issue by arnau-rius** [Shopify/shopify-theme-inspector#48]
### Problem

It is not possible to use this tool in the stores that you _**manage**_ as a Partner.

**Comment by vfonic** [comment]
Same here

**Comment by wizardlyhel** [comment]
Same issue as #32
Most likely that your login credential have a store you own so that you are able to login to the Chrome extension

**Comment by milkbottlelough** [comment]
I'd also like to point out that it is partners/store collaborators that are going to utilise this tool to its fullest potential.  Merchants don't have the time, and in my experience, the technical understanding to use the results from this extension to adjust/refine their theme's liquid implementation.  Also, they are usually too busy doing what they do best which is selling their products.

**Comment by wizardlyhel** [comment]
@milkbottlelough This is actively being work on

**Comment by mdriess** [comment]
Can't express how strongly we'd love to see this! Even without it, this tool has been huge for our merchants; in some cases leading to going from 3 seconds to 1 second load times and doubling the organic search traffic.

Plus, if partners can more easily fix liquid rendering issues with a tool like this having collaborator access support, you guys will save a ton on your Google Cloud bills!! 😄

**Comment by dan-gamble** [comment]
@mdriess [I think this is on its way in.](https://github.com/Shopify/shopify-theme-inspector/pull/53). Might just be a case of waiting for them to cut a release :)

**Comment by wizardlyhel** [comment]
Yes .. it's coming and Google app review is taking much longer this time around to review our app

**Comment by wizardlyhel** [comment]
V 1.0.6 has the fix for profiling liquid for collaborator accounts on managed stores :)
