### ISSUE TITLE
Shopify tab won't load on DevTools

### ISSUE THREAD

**Issue by asmerkin** [Shopify/shopify-theme-inspector#50]
### Problem

I can't make the Shopify tab appear in Chrome Devtools. I'm running this using a staff account with full access to the store. The store uses Shopify plan and it's not a development store. 

### Replication steps

I just do what the docs say. Download the extension, log in with the staff acount, and open devtools. 

### More Information

Can 403 issues ( Gorgias ) be breaking the inspector?

**Comment by wizardlyhel** [comment]
It's really hard to debug anything with this little information. Do you have the chrome version?

**Comment by mdriess** [comment]
@wizardlyhel we are wondering if it is a permissions issue. Are full permissions required? We are asking for just theme access currently.

**Comment by wizardlyhel** [comment]
Are you talking about the chrome tab is is not appearing or are you talking about hitting refresh button doesn't work?

I am going to assume the latter since you are talking about permissions.

Let me double check on the permission setting for shop staff if the staff only have themes permission

**Comment by mdriess** [comment]
The support team informed us today that *Themes* should be the only permission on a staff account to run the inspector. We have intermittent issues here and there but today it worked :) If we can identify any sort of pattern we will pass that along.

**Comment by asmerkin** [comment]
I’ve found that visiting a few pages often work, but the main issue is the index page. After visiting another page and opening the inspector, then I can come back and test the home page.

**Comment by wizardlyhel** [comment]
Solved with version 1.1.0
