### ISSUE TITLE
Cannot profile unpublished themes

### ISSUE THREAD

**Issue by jameslk** [Shopify/shopify-theme-inspector#57]
### Problem

When I try to profile an unpublished theme, I see the profile of the published theme instead.

### Replication steps

1. Preview an unpublished theme (either with a shared preview URL or with `?preview_theme_id` URL param)
2. Open Shopify Theme Inspector
3. Click Load Profile

### More Information

When I inspect the network requests for Shopify Theme Inspector, I see the production URL being used. See the following screenshot:

![Screen Shot 2020-06-03 at 6 16 18 PM](https://user-images.githubusercontent.com/774411/83701538-2705fc00-a5c7-11ea-8c86-d8e71ba02cb6.png)

This seems to be due to the extension pulling the inspected URL from the window variable `Shop.shop`:

https://github.com/Shopify/shopify-theme-inspector/blob/4c0ea7c21696f71e65b1e79190d2a3ee0734bff4/src/devtools.ts#L85

<img width="958" alt="Screen Shot 2020-06-03 at 6 24 14 PM" src="https://user-images.githubusercontent.com/774411/83701782-fe323680-a5c7-11ea-9182-aa63c847da9b.png">

In previous versions, this doesn't seem to be the case: https://github.com/Shopify/shopify-theme-inspector/commit/bc6bb0c4e5c1a1ef7c10dc87646c1d21b46d2e13

**Comment by jameslk** [comment]
A temporary workaround for this is to run the following code in the console:

```js
history.pushState({}, '', '?preview_theme_id=<THEME ID>')
```

**Comment by jameslk** [comment]
Actually now it seems I'm no longer having this issue. I think perhaps the theme ID is passed in a cookie with the request (for the profiling request) and it wasn't the right one before? I'm not sure.

**Comment by lukechadwick** [comment]
I'm also experiencing this error on a duplicate theme, the temp workaround above worked for me.

**Comment by pmourer** [comment]
I believe i am also experiencing this (still) as i am often linked to code that doesn't exist on the unpublished theme i am previewing

**Comment by wizardlyhel** [comment]
Liquid profiling isn't meant for preview links that you share for non-authorized access.

Profiling on preview themes will work on preview accessed from the admin

<img width="959" alt="Screen Shot 2020-07-28 at 3 07 36 PM" src="https://user-images.githubusercontent.com/2319002/88727592-c5ed3700-d0e4-11ea-99a8-73ba19994cc8.png">

It will not work on preview links generated from the preview bar.

<img width="651" alt="Screen Shot 2020-07-28 at 3 11 17 PM" src="https://user-images.githubusercontent.com/2319002/88727771-1795c180-d0e5-11ea-8615-f8f5507a88f9.png">

Links with `.shopifypreview.com` are public links that anyone can access. Liquid profiling is bound to authorized users of the shop

**Comment by jameslk** [comment]
@wizardlyhel I used a Shopify preview URL simply to make the issue more clear, but I was having the same issue with URLs clicked on from inside the Shopify admin.

**Comment by singhsimranjeetg** [comment]
I'm still having the same, above mentioned issue. I tried to preview unpublished theme from admin but it pulls up the profile for published theme.
