### ISSUE TITLE
Collaborator access still not working for client shops

### ISSUE THREAD

**Issue by Benedikt-beeclever** [Shopify/shopify-theme-inspector#59]
If I login as collaborator of a shop I can't profile the website.  The error message in the dev tab always shows the error "This Page cannot be profiled".

**Comment by paul-muckypuddle** [comment]
Also receiving this, despite what the Shopify changlog states.

**Comment by ConduciveMammal** [comment]
Same as above, I'm also unable to profile the vast majority of stores.
One tonight, brand new development store. Fresh copy of Slate's base [starter-theme](https://github.com/Shopify/starter-theme/) (Not using Slate itself, just it's base theme).

**Comment by wizardlyhel** [comment]
* Make sure your extension is at v1.0.7
* If you had logged into the extension before, please log out and login again

If it still isn't working for you, send a message to me with twitter `@wizardlyhel` I'll need to know the shop you have access to in order to dig further

**Comment by ConduciveMammal** [comment]
> If it still isn't working for you, send a message to me with twitter `@wizardlyhel` I'll need to know the shop you have access to in order to dig further

Hey, I've just followed you, can't seem to message you, though, may need to follow me back.
I'm on 1.0.7, I've re-logged in, tried both localhost and via the .myshopify.com URL, preview theme and published theme. Still no luck 😞.

**Comment by wizardlyhel** [comment]
@ConduciveMammal I have follow you back on twitter

**Comment by wizardlyhel** [comment]
The tool doesn't work on development store yet.

With the help of @ConduciveMammal , a workaround to this issue is add yourself as a staff to the development store.

https://github.com/Shopify/shopify-theme-inspector/issues/55
