### ISSUE TITLE
Cannot sign in with Shopify Theme Inspector chrome extension

### ISSUE THREAD

**Issue by RomainB118** [Shopify/shopify-theme-inspector#64]
### Problem

I just discovered the new "speed score" functionnality on my Shopify admin. And as my site has some room for improvment in that matter, I follow the guidelines and I installed the Shopify Theme Inspector extension for Chrome.

But when I tried to use it, I click on the "sign in" button, and it runs indefinitely.

### Replication steps

- I click on the Shopify icon of the Shopify Theme Inspector extension
- I click on the "sign in" button
- I wait... and nothing happens
![Shopify-theme-inspector-problem](https://user-images.githubusercontent.com/70331936/91455618-93209500-e882-11ea-944d-bdba8021f116.jpg)

### More Information

- I am the owner of my shopify store, I am on a paid plan, this is not a development nor a partner store
- I am already loged in my store admin at the time the problem arises
- I am using a free theme (Venture)

**Comment by wizardlyhel** [comment]
Make sure you are using the same email account that you are using as an owner to log into the extension.
The Chrome extension login is separate from the the admin login but that doesn't explain why you cannot login.

Would you able to share the domain url of your store? You can private message me with twitter at [@wizardlyhel](https://twitter.com/wizardlyhel) if you would like to keep this private from the github thread.

**Comment by RomainB118** [comment]
Thank you very much for your quick answer!

The problem is, nowhere am I able to put my email address. The screenshot I provided in my last message is the only thing this extension is showing. Here is what happens when I click on this extension icon:

![sign-in-problem](https://user-images.githubusercontent.com/70331936/91493518-bca7e380-e8b7-11ea-908e-c73cab5b748c.gif)

**Comment by wizardlyhel** [comment]
Oh interesting.

Would you try this?
* Check if the extension is at v1.0.7
* Uninstall the extension and install the extension again

**Comment by RomainB118** [comment]
Thanks @wizardlyhel !

I finally found where is the problem:
- I initially installed the extension by dragging and dropping the folder to the extension tab on Chromium.
- If I use Google Chrome and If I go to the Google chrome extension website and I install it from there, it works! That's weird, because it is on the same page that I downloaded the crx file.

Now, the question is, how can I use it on Chromium ?

**Comment by wizardlyhel** [comment]
This extension is specifically built for Chrome. While other Chromium based (Edge and Opera) browsers can install the extension from Chrome Web Store, we have not test it.

If you compile your own Chromium and tries to install the extension with downloaded the binary, I don't think it will work. This is because you will end up with a different app extension id that Shopify OAuth service is scoped with. This new app extension id is most likely your own unique id for the browser apps.
