### ISSUE TITLE
Can only profile "page" templates

### ISSUE THREAD

**Issue by thegumbyman** [Shopify/shopify-theme-inspector#65]
### Problem

As a partner collaborator I only seem to be able to profile page templates, not collections, products, index, account or cart

### Replication steps

1. Sign in to extension
2. Load store, and open inspector
3. Hit the load profile button on the Shopify tab
4. If it's a page template receive the profile output, otherwise receive the "This page cannot be profiled" error

Page:
<img width="899" alt="page-template" src="https://user-images.githubusercontent.com/1166522/92187462-35e99c80-ee9d-11ea-8aa3-b3b84a190986.PNG">

Any others:
<img width="239" alt="others" src="https://user-images.githubusercontent.com/1166522/92187479-3d10aa80-ee9d-11ea-9277-6fac2c020b97.PNG">

### More Information

I've tried this on two paid stores (one basic, one plus store) and observed the same behaviour.
I have attempted re-installing the extension and signing out and back in without any success.
I've also attempting signing in as the owner of the store without any change.

**Comment by wizardlyhel** [comment]
@thegumbyman Hi, it is possible that the stores you are working are using the new [Storefront Renderer](https://www.shopify.ca/enterprise/reunite).

You can check if the page is rendered by the new Storefront Render by looking for `x-storefront-renderer-rendered: 1` in the response header on the main html document.

We are are working very hard to get the liquid profiling working on the new Storefront Renderer.

**Comment by thegumbyman** [comment]
Thanks @wizardlyhel ... Yes they're using the new renderer. Is there a timeline for compatibility?

**Comment by wizardlyhel** [comment]
No timeline of when will it be completed but you can keep track of this PR #63 

Once that is merged, we have to wait for Google extension review
