### ISSUE TITLE
This page cannot be profiled

### ISSUE THREAD

**Issue by Lucania001** [Shopify/shopify-theme-inspector#67]
Hi Guys,

I have a shopify partner login. I am trying to run shopify-theme-inspector for stores I manage.

However I keep getting the following error

<img width="557" alt="Screenshot 2020-09-17 at 14 12 10" src="https://user-images.githubusercontent.com/5969118/93475074-1cf6d780-f8f0-11ea-8e25-9d2609a72079.png">

Are you able to help at all?

**Comment by wizardlyhel** [comment]
@Lucania001 

* Make sure you do have at least themes permission access as a collaborator
* Make sure you have logged in to the extension with the same email you used as an authorized collaborator account
* Try uninstall and re-install the extension

If none of the above works, tweet me at @wizardlyhel with you shop url and I can take a look

**Comment by wizardlyhel** [comment]
Also, it is possible that the stores you are working are using the new Storefront Renderer.

You can check if the page is rendered by the new Storefront Render by looking for `x-storefront-renderer-rendered: 1` in the response header on the main html document.

We are are working very hard to get the liquid profiling working on the new Storefront Renderer. You may follow the progress on #63

**Comment by Lucania001** [comment]
Thanks, as @wizardlyhel pointed out this is related to #63 so will close this
