### ISSUE TITLE
Receiving 401 code responses while signed into a valid account

### ISSUE THREAD

**Issue by bashunaimiroy** [Shopify/shopify-theme-inspector#72]
### Problem

Hello. I have been trying to work with the Shopify Theme Inspector to inspect an Unpublished theme, on a store to which I am signed in via a Partners Account with Collaborator status and themes access, as mentioned in the docs. 

I was receiving "This page cannot be profiled" errors, and the network tab was showing 401 errors consistently. Eventually, on the advice of a coworker, I signed in and out of my account in the Theme Inspector popup a few times, refreshed / navigated between pages, and I was able to successfully profile pages that hadn't been working before.

However, after doing some other work for a few minutes, I came back to the same page and clicked Load Profile in the plugin again, and received the same "Page Cannot be Profiled" and 401 error. 

### Replication steps

I am not sure how to replicate. As far as I can tell, there were no variables changed, besides waiting 10 minutes in between requests. The best I can say is 

1. Sign into an account with Collaborator Status and themes access on the store
2. Sign in and out and refresh the page until Shopify Theme Inspector starts working
3. wait 10-12 minutes
4. Profile the page again

The screenshots below illustrate the Network requests made by the plugin.

![image](https://user-images.githubusercontent.com/27756206/95622523-ad34c200-0a41-11eb-8e49-9358b8d4293b.png)

![image](https://user-images.githubusercontent.com/27756206/95622735-11578600-0a42-11eb-9de3-b3af8c7ab8d9.png)

### More Information

This theme is not being rendered using the Shopify Storefront Renderer.

I am still signed into the same account, that hasn't changed.

Thanks for your time.

**Comment by wizardlyhel** [comment]
Hmm .. I wonder if the Oauth token isn't being refreshed properly

**Comment by bashunaimiroy** [comment]
Is there something I can do on my side to help test or fix this?

**Comment by wizardlyhel** [comment]
I'll need to do some double checking on Shopify's oauth policy and find a chance to replicate this issue - A bit busy these couple days.

**Comment by bashunaimiroy** [comment]
Of course. Thank you!

**Comment by wizardlyhel** [comment]
@bashunaimiroy This should be fixed with the latest version. If it isn't, feel free to reopen this issue.

**Comment by bashunaimiroy** [comment]
Thanks Helen.
