### ISSUE TITLE
Seems to slow performance of the page to a crawl

### ISSUE THREAD

**Issue by Tiberriver256** [Shopify/shopify-theme-inspector#73]
When I visit the site without the add-in installed:
Render time: 2.27s

When I visit the site with the add-in installed:
25.2s

Is this much of a slowdown expected?

**Comment by wizardlyhel** [comment]
The extension itself shouldn't slow down site navigation.

What do you mean by `without the add-in installed`?

**Comment by Tiberriver256** [comment]
I mean it quite literally. Like right-click the extension icon in the top right and click uninstall. I'll see if I can grab a video of it for you.

**Comment by wizardlyhel** [comment]
Yes please.

Slowing down browser based on installing the extension is not expected.

**Comment by Tiberriver256** [comment]
Hey @wizardlyhel,

Thank you for the help. I think for some reason it was forcing the Cloudflare cache to be bypassed which showed me the 'actual' performance of the site 😱. I reinstalled the extension to show you but couldn't reproduce the same behavior. Watching requests in Fiddler though it looks like the extension loads the page with profile_liquid=true which seems to set the CF-Cache-Status header to Dynamic which makes the page render similar to what it would be for a CF-Cache-Status=miss.

I only noticed because I hit a page that was a CF-Cache-Status=miss without the extension installed and it was equally slow. I'll close the issue out and get to work on improving this crazy slow performance! Thanks for the extension.

**Comment by wizardlyhel** [comment]
Yea - the extension does purposely request profiling on a cache miss. Cache miss isn't a bad thing, especially in ecommerce, where Shopify needs to build a new rendered page when there is shop changes (new product added, inventory out of stock, ..etc)

So - fixing performance on cache miss will mean that customer will have a better shopping experience even when the shop is changing
