### ISSUE TITLE
Flamegraph no longer visible under sections

### ISSUE THREAD

**Issue by henrybarn** [Shopify/shopify-theme-inspector#74]
### Problem

The flamegraph now shows one large flame for the entire section file and no longer breaks it down to liquid inside those sections

### Replication steps

Tested on multiple stores

### More Information

I think this might be related to a recent update, I haven't seen this issue before

**Comment by dan-gamble** [comment]
Glad this wasn't just me. I was also getting it for `{{ content_for_index }}`

**Comment by dan-gamble** [comment]
![image](https://user-images.githubusercontent.com/7152041/96184923-0c5a7100-0f31-11eb-8f8c-aaf0460aab34.png)

![image](https://user-images.githubusercontent.com/7152041/96185041-3ad84c00-0f31-11eb-8037-7eaa532330e9.png)

These are a few examples of what I'm getting now

**Comment by wizardlyhel** [comment]
Hey - We are aware and we are working on a fix for this

**Comment by wizardlyhel** [comment]
This should be fixed (No need to update extension)
