### ISSUE TITLE
How to log out of the extension

### ISSUE THREAD

**Issue by imCorfitz** [Shopify/shopify-theme-inspector#76]
### Problem

I logged in using one partner account when using for one site, but I am now trying to debug another site, where I have been provided a separate account. How do I log out of the extension and back in?

**Comment by ImCorfitz** [comment]
Well - one solution is to remove the extension, quit the Chrome app and reinstall the extension afterwords.. Just seems overly complicated.

**Comment by wizardlyhel** [comment]
Hey, I am aware of this issue. I am quite certain the extension is not refreshing token when it should and remove saved token when it should after signed out. This is a related issue to https://github.com/Shopify/shopify-theme-inspector/issues/72

**Comment by wizardlyhel** [comment]
Should be resolved
