### ISSUE TITLE
Software can't run

### ISSUE THREAD

**Issue by lmy56912** [Shopify/shopify-theme-inspector#78]
### Problem

/* Succinct outline of the problem or request. */

### Replication steps

/* How to replicate the problem. Include screenshots or video if relevant. */

### More Information

/* Any additional information which might be helpful. */

**Comment by lmy56912** [comment]
When I open the shopify store and plan to run the software, "Open a Shopify store to use this extension. If you are already on a Shopify store reload the page.", how can I solve？

**Comment by wizardlyhel** [comment]
Hi,

1. When you are on a Shopify store
2. Make sure you are logged in with an ID that has staff access to shop or a collaborator access to shop (minimum permission: themes)
<img width="259" alt="Screen Shot 2020-12-07 at 8 48 32 AM" src="https://user-images.githubusercontent.com/2319002/101379344-01ed9100-3869-11eb-939d-2d2bb037dd66.png">
2. Open the Chrome DevTools with right-click to open the menu and click on inspect
3. Look for a tab that labelled Shopify
4. Click on the refresh button to start profiling liquid
<img width="434" alt="Screen Shot 2020-12-07 at 8 47 21 AM" src="https://user-images.githubusercontent.com/2319002/101379241-ea160d00-3868-11eb-810d-492d500d9690.png">
