### ISSUE TITLE
Cannot profile shop user account pages

### ISSUE THREAD

**Issue by JamiesonRoberts** [Shopify/shopify-theme-inspector#79]
### Problem

Running the latest version of the tool I am able to run the flame reports on all of the pages of the site, except for those in the /account/ path, so the login, list of past orders etc. I've logged out and then back in again to my admin account, I've tried a fresh/different computer. I'm on the most recent version of chrome and the plugin.

### Replication steps

Go to a dev shop, and try to run the flame report on /account or /account/login or other such pages and receive a "This page cannot be profiled" error

**Comment by wizardlyhel** [comment]
You are correct. This extension cannot profile login pages .. yet. I'll find some time to fix this.

**Comment by JamiesonRoberts** [comment]
@wizardlyhel amazing, thank you very much. Is there anything I can do to assist on this?
