### ISSUE TITLE
Cannot profile using staff account with the same email logged in for chrome extension

### ISSUE THREAD

**Issue by astridchin** [Shopify/shopify-theme-inspector#85]
Cannot profile using Staff Account with the **same email** logged in for chrome extension (mine is NOT a development store)
Just getting a "This page cannot be profiled" message..... 
Any insight please?
I have a lighthouse score of 13, so pretty desperate to look into the speed details with this extension

**Comment by astridchin** [comment]
anyone any idea please?

**Comment by wizardlyhel** [comment]
@astridchin I'll need the store url before I can investigate. You can send me a private message with twitter `@wizardlyhel` if you are not comfortable posting in github thread.

**Comment by wizardlyhel** [comment]
hey @astridchin

We recent resolved an issue with regards to login. Could you try again by logging out and logging again and see if you can profile the page?
