### ISSUE TITLE
This page cannot be profiled

### ISSUE THREAD

**Issue by aisaacs** [Shopify/shopify-theme-inspector#86]
### Problem

Not a development store. Tested with all existing store accounts, including store owner. Tried removing and reinstalling extension twice. Always the same response, "This page cannot be profiled". 

### Replication steps

Attempt to profile the store. 

### More Information

Every time I press the profile button, the extension pops up the login window. No matter which user I log in with, the response is the same - "This page cannot be profiled". This is true for any page on the store, homepage, cat pages, pdp. In the console I have noticed the following, which however I don't think is related:

"DevTools failed to load SourceMap: Could not load content for https://cdn.shopify.com/shopifycloud/storefront-recaptcha-v3/v0.1/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

**Comment by aisaacs** [comment]
To add on to this, it would appear that logging in is not successful since every attempt to profile attempts a new login.

**Comment by aisaacs** [comment]
I have found a workaround.

1. Uninstall the extension, and reinstall
2. Log in immediately by clicking on the extension icon in the toolbar (NOT by attempting to profile immediately)
3. Profiling now works correctly.

**Comment by wizardlyhel** [comment]
Thanks for reporting this issue
