### ISSUE TITLE
Slow store cannot run profiler on any page

### ISSUE THREAD

**Issue by icantrank** [Shopify/shopify-theme-inspector#94]
### Problem

When trying to profile all pages on a live site - I get the error 'this page cannot be profiled'.
Inspecting the devtools frame shows errors parsing the json from #liquidProfileData:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $jscomp.generator.Engine_.program
```

I have looked at the response from `page?profile_liquid=true` and extracted `#liquidprofiledata` myself, and it parses as json just fine in my ides formatter but not with JSON.parse.
It is 3mb of json / 52k lines formatted. Maybe that has something to do with it? JSON.parse has some hard limits and we have a lot of lines of code.

I saw in another issue that @wizardlyhel asked someone to twitter DM the site to debug further - would be happy to do that if it would help figure out the problem.

**Comment by wizardlyhel** [comment]
That's a lot of JSON data. I didn't anticipate that we would hit the limits of `JSON.parse` but I don't think Chrome would get stuck on 3mb of JSON data unless you are in incognito mode. Are you able to identify the area of the string where the syntax error is generated? The error should tell you at what character position it failed at.

**Comment by mgmanzella** [comment]
👋 closing as we haven't received the info helen asked for, please re open this issue with that info if this is still a problem
